api/models/__init__.py
from .base import db
from .person import Person

__all__ = ["Person", "db"]

api/models/base.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

api/models/person.py
from flask_login import UserMixin

from api.models.base import db


class Person(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(1000))

api/models/user.py
from .base import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(1000))

api/forms/login.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import InputRequired, Email, Length


class LoginForm(FlaskForm):
    email = StringField('Email', 
            validators=[Email("This field requires a valid email address")], 
            render_kw={'placeholder': 'Email', 'type': 'email'})
    password = PasswordField('Password', 
            validators=[InputRequired(), Length(min=4, max=10)], 
            render_kw={'placeholder': 'Password', 'type': 'password'})
    remember = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class RegisterForm(FlaskForm):
    email = StringField('Email', 
            validators=[Email("This field requires a valid email address")], 
            render_kw={'placeholder': 'Email', 'type': 'email'})
    password = PasswordField('Password', 
            validators=[InputRequired(), Length(min=4, max=10)], 
            render_kw={'placeholder': 'Password', 'type': 'password'})
    name = StringField('Name', 
            validators=[InputRequired(), Length(min=5, max=20)], 
            render_kw={'placeholder': 'Name'})
    submit = SubmitField('Sign In')

api/__init__.py
import os
from flask import Flask
from flask_login import LoginManager


from api.config import config


def create_app():
    app = Flask(__name__)
    env = os.environ.get("FLASK_ENV", "dev")
    app.config.from_object(config[env])

    # Register db to the app
    from api.models import db
    db.init_app(app)

    login_manager = LoginManager()
    login_manager.login_view = 'login.login_route'
    login_manager.init_app(app)

    from api.models import Person

    @login_manager.user_loader
    def load_user(user_id):
        return Person.query.get(int(user_id))



    # Register blueprints for main sections of the app

    from .blueprints.login import login as login_blueprint
    app.register_blueprint(login_blueprint)

    from .blueprints.generic import generic as generic_blueprint
    app.register_blueprint(generic_blueprint)

    return app

api/blueprints/generic.py
from flask import Blueprint, render_template

from api.models.base import db

generic = Blueprint('generic', __name__)


@generic.route('/')
def index():
    return render_template('index.html')

api/blueprints/login.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash

from api.models.base import db
from api.models.person import Person

from api.forms.login import LoginForm, RegisterForm


login = Blueprint('login', __name__)


@login.route('/login', methods=['GET', 'POST'])
def login_route():
    form = LoginForm()
    if not form.validate_on_submit():
        return render_template('login.html', form=form)

    email = form.email.data
    password = form.password.data
    remember = True if form.remember.data else False

    person = Person.query.filter_by(email=email).first()

    if not person or not check_password_hash(person.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('login.login_route'))

    login_user(person, remember=remember)
    return redirect(url_for('login.profile'))


@login.route('/signup', methods=['POST', 'GET'])
def signup():
    form = RegisterForm()
    if not form.validate_on_submit():
        return render_template('register.html', form=form)

    email = form.email.data
    password = form.password.data
    name = form.name.data

    # check if the user is already registered
    person = Person.query.filter_by(email=email).first()
    if person:
        flash('Email address already exists')
        return redirect(url_for('login.signup'))

    # if not, register the user
    new_user = Person(email=email, name=name, password=generate_password_hash(password, method='sha256'))

    db.session.add(new_user)
    db.session.commit()
    flash('Thanks for registering! Please login')
    return redirect(url_for('login.login_route'))


@login.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('generic.index'))


@login.route('/profile')
@login_required
def profile():
    return render_template('profile.html', name=current_user.name)

api/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-info is-fullheight">
    
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div class="navbar-brand">
                        <a class="navbar-item">LOGO </a>
                        <span class="navbar-burger burger" data-target="navbarMenuHeroA">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                    </div>

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('generic.index') }}" class="navbar-item">
                                Home
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('login.profile') }}" class="navbar-item">
                                Profile
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('login.login_route') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('login.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('login.logout') }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
                {% block content %}
                {% endblock %}
            </div>
        </div>

    </section>
</body>

</html>

api/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Flask Login Example
</h1>
<h2 class="subtitle">
  Easy authentication and authorization in Flask.
</h2>
{% endblock %}

api/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}
        </div>
        {% endif %}
        {% endwith %}

        <form method="POST" action="">
            {{ form.hidden_tag() }}

            <div class="field">
                <div class="control">
                {{ form.email(class_="input is-large") }}<br>
                {% for error in form.email.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
                </div>
            </div>

            <div class="field">
                <div class="control">
                {{ form.password(class_="input is-large") }}<br>
                {% for error in form.password.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
                </div>
            </div>

            <div class="field">
                <label class="checkbox">
                {{ form.remember() }} {{ form.remember.label }}
                </label>
                {{ form.submit(class_="button is-block is-info is-large is-fullwidth") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

api/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
	Welcome, {{ name }}!
</h1>
{% endblock %}

api/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}. Go to <a href="{{ url_for('login.login_route') }}">login page</a>.
        </div>
        {% endif %}
        {% endwith %}

        <form method="POST" action="">
            {{ form.hidden_tag() }}

            <div class="field">
                <div class="control">
                    {{ form.email(class_="input is-large") }}<br>
                    {% for error in form.email.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
            </div>

            <div class="field">
                <div class="control">
                    {{ form.name(class_="input is-large") }}<br>
                    {% for error in form.name.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
            </div>

            <div class="field">
                <div class="control">
                    {{ form.password(class_="input is-large") }}<br>
                    {% for error in form.password.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
            </div>

            <div class="field">
                {{ form.submit(class_="button is-block is-info is-large is-fullwidth") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}